
interval: 
    type: time
    min: 1
    max: 3600
    value: 10


iterations:
    type: int
    min: 1
    value: 100 


persistentcamera:
    type: boolean
    value: True

pc_pre_wait:
    type: float
    min: 0
    max: 30
    value: 5

pc_post_wait:
    type: float
    min: 0
    max: 30
    value: 5


secondexposure:
    type: boolean
    value: True

se_use_threshold:
    type: boolean
    value: True

se_threshold:
    type: float
    min: 0
    max: 20
    value: 10.3

se_expcompensation_1:
    type: float
    min: -10
    max: 10
    value: 1

se_expcompensation_2:
    type: float
    min: -10
    max: 10
    value: -5


autofocus:
    type: boolean
    value: True


# --------------------------------------------------------

log:
    basedir: "."
    level: DEBUG
    format: "%(asctime)s | %(levelname)-7s | %(message)s"