
interval: 
    type: time
    min: 1
    max: 3600
    value: 3712

iterations:
    type: int
    min: 1
    value: 100 

secondexposure:
    type: boolean
    value: False

se_threshold:
    type: float
    min: 0
    max: 20
    value: 10.3

se_expcompensation_1:
    type: float
    min: -10
    max: 10
    value: 1

se_expcompensation_2:
    type: float
    min: -10
    max: 10
    value: -5

autofocus:
    type: boolean
    value: True