

interval: 
    type: time
    min: 1
    max: 3600
    value: 180


iterations:
    type: int
    min: 1
    value: 1000 


intervalcamera:
    type: boolean
    value: True

ic_pre_wait:
    type: float
    parent: "intervalcamera"
    min: 0
    max: 30
    value: 12

ic_post_wait:
    type: float
    parent: "intervalcamera"
    min: 0
    max: 30
    value: 10


secondexposure:
    type: boolean
    value: True

se_use_threshold:
    type: boolean
    parent: "secondexposure"
    value: True

se_threshold:
    type: float
    parent: "secondexposure"
    min: 0
    max: 25
    value: 10.3
    # value: 25

se_expcompensation_1:
    type: float
    parent: "secondexposure"
    min: -10
    max: 10
    value: 1

se_expcompensation_2:
    type: float
    parent: "secondexposure"
    min: -10
    max: 10
    value: -5


autofocus:
    type: boolean
    value: True


min_battery:
    type: int
    min: 0
    max: 25
    value: 2 


# --------------------------------------------------------

image_dir_primary:
    path: "/media/external_storage"

image_dir_secondary:
    path: "RAW"

log:
    basedir: "."
    filename_debug: "debug.log"
    filename_info: "info.log"
    level: DEBUG
    format: "%(asctime)s | %(levelname)-7s | %(message)s"